### ISSUE TITLE
Whitelist Backend not working upon fresh install

### ISSUE THREAD

**Issue by mikemunevar** [bitExpert/magento2-force-login#110]
After doing a manual install of this on my Magento 2.1.8 system, I get the following error with my marketplace plugin:

`		Incorrect dependency in class Ced\CsMarketplace\Controller\Adminhtml\Vproducts\Vproductgrid in /opt/bitnami/apps/magento/htdocs/app/code/Ced/CsMarketplace/Controller/Adminhtml/Vproducts/Vproductgrid.php
\Magento\Framework\App\Response\RedirectInterface already exists in context object
Total Errors Count: 1
Interception cache generation... 7/7 [============================] 100% 3 mins 216.0 MiB
Generated code and dependency injection configuration successfully.
`

However, upon loading the Customers->Whitelist menu I get:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'bitnami_magento.bitexpert_forcelogin_whitelist' doesn't exist, query was: SELECT `main_table`.* FROM `bitexpert_forcelogin_whitelist` AS `main_table`

Is that right?  A full table was not generated during install?

**Comment by shochdoerfer** [comment]
Thanks for reporting this issue. Are you using a db table prefix in your Magento configuration?

**Comment by mikemunevar** [comment]
I'm not sure. I did not specify a prefix when I installed Magento2.1 so it may be there by default?  How can I be certain?

**Comment by shochdoerfer** [comment]
Could you please check if the database table does indeed not exist?

**Comment by mikemunevar** [comment]
Hi Stephan, I did run phpmyadmin, and searched for tables named bitexpert, forcelogin and whitelist, but wasn't able to find any.  I followed the directions in the readme for installing(downloaded code, extract, enable module, compile, upgrade, then flush cache)

What can I try next?

**Comment by websharp** [comment]
Hi @mikemunevar ,

which version of the module do you use? If you are able to access your magento installation, you could also try to install by composer instead of manually download the code, so the correct version of the module  in relation to your Magento version is installed (`composer.phar require bitexpert/magento2-force-customer-login`).

Best regards!

**Comment by mikemunevar** [comment]
Stephan, I went ahead and tried doing a composer install, but actually ended up making things worse, as the plugin was then installed and enabled twice, and the `./bin/magento` command was failing because of that.   After restoring to an older version of the server, I was able to perform the fresh install using composer.  I believe it installed an older version of the plugin.  All works now. Hope my experience can help others.

**Comment by shochdoerfer** [comment]
Sorry to hear this. The best was is indeed the Composer installation. If you run into more issues, let us know.

**Comment by websharp** [comment]
Hi @mikemunevar ,

thank you for your Feedback. In the current master version, the namespace is typed correctly, so maybe you read from an older installation guide? The correction was made due to Magento 2.2.x requirements upon the namespace declaration.

Did you run the following commands (in development mode)?
```
bin/magento module:enable BitExpert_ForceCustomerLogin
bin/magento setup:upgrade
bin/magento cache:flush
```

Best regards!
