### ISSUE TITLE
Whitelist entire website or store view

### ISSUE THREAD

**Issue by salgua** [bitExpert/magento2-force-login#14]
Hi,

I'm trying to add to the whitelist an entire site view, but it doesn't work. I tried to add "/" or ".*" or "*", specifying the desired site view, nothing, it doesn't work. Could you help me?

**Comment by websharp** [comment]
Hi @salgua ,

thanks for reaching out! I understand you want to whitelist an entire store with a single rule, so a whitelist wildcard entry should suffice your needs, declared as regular expression like this "/.*" or ".*" .  

This was intended from the beginning, but the quotation of the entry rules was performed too strong. I fixed this with PR #15 and released version 1.2.1 with the fix. Can you please update to the latest version and try again? Would be great if you could provide some feedback the fix is working or if you encounter some issues furthermore. Perhaps you have to clear your caches before the update can become effective in your magento2 installment.

**Comment by salgua** [comment]
Hi @websharp, I update your plugin to the latest release (1.2.1) and cleared the cache. I tried with regular expressions like ".*" and "/.*", nothing, it doesn't work. Any suggestion is welcome, maybe I am doing something wrong.

**Comment by websharp** [comment]
Hi @salgua ,

many thanks for your feedback. After recreating your situation, I found another bug not building up the collection filter statement correctly which resolves in ignoring store specific rules. I published a new release 1.2.2, which you can give a try - has worked for me in a Magento 2.0.7 environment and should also work with Magento 2.1+ installments.

As always, happy to hear if the issue is fixed or if there have any other issues occurred.

**Comment by salgua** [comment]
Hi @websharp,

just tried your work, thank you very much, it seems to work fine!

Thank you again!
Salvatore
