### ISSUE TITLE
Module not enabled but redirect to homepage

### ISSUE THREAD

**Issue by nelero** [bitExpert/magento2-force-login#182]
If we choose enabled NO on admin, having errors login in redirect visitor to homepage instead of staying on customer/account/login page

Steps to reproduce :
enable module via SSH
choose NO on backend config for enabled option
going to /customer/account/login
email : nonexistantmail@nowhere.com
password : anything

expected results : 
- error message on customer/account/login

Actual results : 
- visitor is redirected to homepage and error message appears here.

**Comment by shochdoerfer** [comment]
@nelero thanks for reporting this issue. Any chance you could provide a PR to fix this issue?

**Comment by SplendidGoT** [comment]
Same problem here with a clean install on Magento 2.3.2.

**Comment by websharp** [comment]
@nelero @SplendidGoT we added some fixes to the master, do you mind testing your issue, if everything works fine now or report any new issue occured?

**Comment by taskula** [comment]
> @nelero @SplendidGoT we added some fixes to the master, do you mind testing your issue, if everything works fine now or report any new issue occured?

The issue still stands. I noticed this in 3.1.0 and updated to 4.1.0 and the issue is still there. If you disable the plugin altogether, everything works as expected.

Additionally, if your login is successful, your customers will always get redirected to the store main page which is bad if you want to redirect your customers back to the page they clicked login at.
