### ISSUE TITLE
Customer groups

### ISSUE THREAD

**Issue by dutchwave** [bitExpert/magento2-force-login#28]
Wouldn't it be great if a page/storefront can also be whitelisted based on Customer Group.
Any one planning to add this functionality?

**Comment by websharp** [comment]
Hi @dutchwave ,

thank you for sharing your thoughts! I thought about this feature a while ago and initiallay discarded the idea at first, due to the fact you have to be logged in to now the users Customer Group. On second thought this can be realized after all, but needs some more conceptional thinking. I think this feature fits well in this module, but must be separated from the initial whitelist which controls when to be forced to login in general. So I think we will implement this feature in the near future :)

**Comment by websharp** [comment]
This issue is placed in our internal system, so I'm closing this issue here. We are planning on bringing this feature with an additional module.
