### ISSUE TITLE
Static matching strategy could ignore ending slash

### ISSUE THREAD

**Issue by maderlock** [bitExpert/magento2-force-login#75]
The static strategy would be a good one to use in many simple cases, except that when trying it out I found that about half my links failed because a slash was appended. I should almost certainly canonicalise my links, but this still feels a little fragile.

Would it be better to allow an options slash on the end of links that do not have one, or perhaps you think that in this case we should be using regex (my solution here) or doubling every rule to match slashes.

**Comment by websharp** [comment]
Hi @maderlock ,

thanks for the feedback, much appreciate it! 

I think the best way would be to canonicalise, because I think at the end "/foo/bar" and "/foo/bar/" representing the same endpoint. Is there any reason why you think this could be fragile?

I think doubling every rule would be an overhead mess, and regex should be for more complex stuff.

**Comment by maderlock** [comment]
No, I don't think that would be fragile. I cannot think of a useful case where you would want a bareword to differ from that same bareword plus a slash - nobody would find that intuitive I think

**Comment by websharp** [comment]
Fixed this issue with RC3 of v2.1.0

**Comment by maderlock** [comment]
That's great, thanks. I'll pull this into the site I'm working on and see how it fares in user testing.
