### ISSUE TITLE
404 pages do not show when logged out

### ISSUE THREAD

**Issue by mattgreenfield** [bitExpert/magento2-force-login#83]
My 404 pages are working fine when a user is logged in but are white screening when logged out. I've disabled this plugin and the 404 pages work fine again.

- Is this something that I need to whitelist?
- Is there any way to serve a different 404 page to users who are logged in Vs those who aren't (even just with a class on the body/CSS)?

Thanks for your help,

**Comment by websharp** [comment]
Hi @mattgreenfield ,

you can add the Url for the 404 page to the whitelist entries as a new entry (then clear cache, etc.), this should solve your issue. Currently the module does not let you configure the handling of serving custom 404 error pages on certain conditions.

Best regards!

**Comment by mattgreenfield** [comment]
Thanks @websharp, 
I've added "/no-route" to the white list and can now get to that page ok. However, if I visit "[myDomain]/speling-mistke" (or any other page that should 404) I get the white screen. It's as if the logic checking the whitelist happens before the redirect/routing.

Is this the expected behaviour? Are you able to replicate it?

Thanks again,

**Comment by jaminion** [comment]
@mattgreenfield you're definitely correct that the whitelist checking occurs before noroute handling. The force login module instantiates a controller to handle the request, however since this happens outside of the normal M2 routing process, another controller gets instantiated by the routing process afterwards, and overwrites the response status code with 404, although it doesn't overwrite the response body (which is why you don't redirect even though a Location header is sent back but you see a blank screen).

The next time you go to that same url with the fpc enabled, you will see a cached version of the response from the no-route handler that was generated the first time but not sent, likely your 404 cms page content. I'm not completely certain of the path for this but I'm not nearly as interested in it as the first-time hit on that should-be-404 page.

I'm looking at handling this for now by running another module which just wraps plugins around two functions:

* bitExpert\ForceCustomerLogin\Controller\LoginCheck->execute()
    * if redirecting, adding a flag to the request object to check later
* Magento\Framework\App\Router\NoRouteHandler->process()
    * if flag exists on request object from above, skip normal execution of this function

In this case we are redirecting to our specified page on every 404 request, and that definitely may not be suitable for all/most use cases for this extension, which is why I'm not forking/pr for any of that, because there's likely considerably more configuration to be done to make that more generally useful. You can basically see this effect adding a die() at the end of the LoginCheck->execute() method. I'm not sure how to otherwise signal the internal routing to stop and prevent the noroute processing.

**Comment by websharp** [comment]
Hi @mattgreenfield and @jaminion ,

thanks for your contribution. I provided a fix for this issue with PR #88 , feel free to review and give me feedback. I may merge this fix in next days.

**Comment by mattgreenfield** [comment]
Thanks @websharp. I'm afriad don't know enough PHP/Magento to comment with anything of worth to that PR, but thanks again.

**Comment by shochdoerfer** [comment]
Not sure if it helps, but I just came across this blog post on [How Magento 2 Decides If A Page Is Cacheable](https://maxchadwick.xyz/blog/how-magento-2-decides-if-a-page-is-cacheable).
