### ISSUE TITLE
Disable registration isn't possible

### ISSUE THREAD

**Issue by evilprophet** [bitExpert/magento2-force-login#84]
I would like to disable possibility to register new user(for B2B shop).
I removed /customer/account/create from whitelist but registration is still possible because default rule Customer Account Dashboard (/customer/account) is also match for registration url.

**Comment by websharp** [comment]
Hi @evilprophet ,

I think the solution is rather simple to solve with the newest version of the module, where you can set the strategy of the whitelist rule to _static_ instead of _regex_. There should be the problem however, that the UI does not allow you do enter the edit form for these rules (maybe we should skip the prohibition as there is a reset default functionality by now). 

If you have direct access to the database, you can change the strategy yourself in the table _bitexpert_forcelogin_whitelist_ for now as a workaround.

Best regards
